# version: '3.9'

# services:
#   # -------------------------------
#   # PostgreSQL Service
#   # -------------------------------
#   postgres:
#     image: postgres:16
#     container_name: postgres_db
#     restart: always
#     env_file: .env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     # ports:
#     #   - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   # -------------------------------
#   # Redis Service
#   # -------------------------------
#   redis:
#     image: redis:7
#     container_name: redis_server
#     restart: always
#     env_file: .env
#     command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
#     # ports:
#     #   - "6379:6379"
#     volumes:
#       - redis_data:/data

#   # -------------------------------
#   # Node.js App
#   # -------------------------------
#   app:
#     build: .
#     container_name: node_app
#     restart: always
#     env_file: .env
#     ports:
#       - "8000:8000"
#       - "5555:5555"
#     depends_on:
#       - postgres
#       - redis
#     volumes:
#       - .:/usr/src/app
#     command: npm run dev

# volumes:
#   pg_data:
#   redis_data:





# render deployment
version: '3.9'

services:
  app:
    build: .
    container_name: node_app
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
      - "5555:5555"
    command: npm run start
